### ISSUE TITLE
Container Attach w/ a TTY seems broken

### ISSUE THREAD

**Issue by pdevine** [docker/engine-api#147] opened 2016-03-14 22:01 UTC
When attaching to a container, I can attach to a container when I'm not using the TTY, however I use the TTY it doesn't return any data.

Here's the relevant code.  If you uncomment the Tty line, at least for me, it exhibits the behaviour.  If its commented out, everything works fine.

    cfg := &container.Config{
        AttachStdin:  false,
        AttachStdout: true,
        AttachStderr: true,
        Image:        <image name>,
        Labels:       map[string]string{},
        //Tty:          true,
    }
    hostCfg := &container.HostConfig{}
    netCfg := &network.NetworkingConfig{
        EndpointsConfig: map[string]*network.EndpointSettings{},
    }

    resp, err := client.ContainerCreate(cfg, hostCfg, netCfg, <image name>)
    if err != nil {
        log.Fatalf("Couldn't create container '%s': %s", <image name>, err)
    }
    cId := resp.ID
    aResp, err := client.ContainerAttach(types.ContainerAttachOptions{
        ContainerID: cId,
        Stream:      true,
        Stdin:       false,
        Stdout:      true,
        Stderr:      true,
    })
    if err != nil {
        log.Fatalf("Couldn't attach to container: %s", err)
    }

    if err = client.ContainerStart(cId); err != nil {
        log.Error("There was a problem running the container")
        return 1, err
    }

    go func() {
        defer aResp.Close()
        stdcopy.StdCopy(os.Stdout, os.Stderr, aResp.Reader)
    }()

    rc, err := client.ContainerWait(cId)
    if err != nil {
        log.Errorf("Error waiting for container to finished: %s", err)
        return rc, err
    }

**Comment by calavera** [comment] 2016-03-14 22:50
I think the problem is that you're using the `stdcopy` package for the TTY output. See my example in the following gist, I get an output whether TTY is on or off:

https://gist.github.com/20cfa8a5e025df56da08

You can see we use the same logic in Docker's CLI: https://github.com/docker/docker/blob/4a9523adc90de8fea1de23b5e33ae184bdd9f25e/api/client/hijack.go#L16-L21

**Comment by calavera** [comment] 2016-03-14 23:43
I'll add an example about how to use this shortly, but I'm going to close this since it's not a bug. Thanks for the clear report @pdevine.

**Closed by calavera** 2016-03-14 23:43 UTC
